spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9301/hf_edit_tool_sit?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      validation-query: select 1
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  main:
    allow-bean-definition-overriding: true
  data:
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password: neo4j
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yinww.demo.springboot2.demo006.domain
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8665
flowable:
  async-executor-activate: false
doc-frame-service:
  env-name: tools_sit
  # 路径注意大小写
  upload-path: /application/tools/resource/doc
  #  download-path: D:\file\download\
  file-pdf-save-path: /application/tools/resource/pdf

  #  项目路径
  project-file-path: /application/tools/resource/projectFile
  #  上传文件解析暂存路径
  doc2html-path: /application/tools/resource/html
  #  上传文件解析暂存路径
  docUnzip-path: /application/tools/resource/unzip
  #  公司信息路径
  company-path: /application/tools/resource/company
  #  头像路径
  headImg-path: /application/tools/resource/headImg
  #  文章内图片存放路径
  pic-path: /application/tools/resource/docImg
  #  静态资源访问的地址
  static-resource-path: http://tools.nebulaedata.cn
  #  参数资源存放路径
  annex-path: /application/tools/resource/annex
  #  段落对比路径
  compare-path: /application/tools/resource/compare
  compare-path-local: /application/tools/resource/compare
  #  文档下载路径
  download-path: /application/tools/resource/download
  #  批次文件路径
  batch-file-path: /application/tools/resource/batchFile
  #  批次文件路径
  upload-json-path: /application/tools/resource/upload_json_path
  #  数据管理-上传excel文件
  upload-dm-data-path: /application/tools/resource/upload_dm_excel_path
# 外部端口调用
do-post:
  dfb-url: http://dfb.nebulaedata.cn